### ISSUE TITLE
Delay settings doesn't saves

### ISSUE THREAD

**Issue by Flashwalker** [degecko/prevue#10]
Delay settings doesn't saves.
Hover event doesn't show popup.
Default browser drag action triggered first.

Ungoogled-Chromium 107

**Comment by degecko** [comment]
The extension uses the Chrome Sync API to store its settings. I'm not sure, but I suppose something called "Ungoogled Chromium" doesn't include such an API, as the authentication process belongs to Google.

I'll try to store the settings locally when that API is not available, but it will take a while.

**Comment by Noah1995** [comment]
你可以试一下Link Previewer
我用过的目前只有这个扩展有防止当前页面跳转
但是没有Prevue Popup操作逻辑好
![image](https://user-images.githubusercontent.com/25548230/208246905-12fd172f-8198-4b1c-b4bb-e75381fb1d37.png)

**Comment by degecko** [comment]
Closed. Chose to only rely on the Chrome Storage API as I'm trying to keep the code clean for Chrome Web Store and Firefox Add-ons moderators to allow the extension to be published to their official stores.

Sorry, you'll have to use Google Chrome or another version which implements the [chrome.storage](https://developer.chrome.com/docs/extensions/reference/api/storage) API.

**Comment by Flashwalker** [comment]
> Closed. Chose to only rely on the Chrome Storage API as I'm trying to keep the code clean for Chrome Web Store and Firefox Add-ons moderators to allow the extension to be published to their official stores.
> 
> Sorry, you'll have to use Google Chrome or another version which implements the [chrome.storage](https://developer.chrome.com/docs/extensions/reference/api/storage) API.

Sorry, but sounds silly. Most extensions (if not all of them) have no problem with either storing settings on Ungoogled Chromium, or moderators
