### ISSUE TITLE
Hover option not working

### ISSUE THREAD

**Issue by boromyr** [degecko/prevue#13]
In Edge key + hover options don't work. The only trigger that works is the Drag.
I tried many combinations:
![image](https://github.com/degecko/prevue/assets/52782032/46b2da44-6f98-44a8-bccd-4999011ff59e)

**Comment by boromyr** [comment]
Is there any chance that this extension will be maintained?

**Comment by DavidGP** [comment]
Is this abandoned? I can't get it to work in any way.

**Comment by boromyr** [comment]
try version 0.3.2

**Comment by DavidGP** [comment]
Where? And the current version is 0.4.6, so you want me go back to an old version?

**Comment by boromyr** [comment]
https://github.com/degecko/prevue/releases/tag/0.3.2
It goes back to the previous version, I used this one for my fork and it works much better.

**Comment by DavidGP** [comment]
That's the source, do I have to compile that or something?

**Comment by boromyr** [comment]
no you can upload it directly, just choose the folder corresponding to your browser, go to src/ and upload the folder for firefox or chromium

**Comment by DavidGP** [comment]
Wow, thanks. What an awesome extension. Do you know anything about the background why the latest version doesn't work, and whether it has been abandoned?

**Comment by boromyr** [comment]
I can share my fork, it works with alt+up to activate the preview, and on Google results the preview opens automatically after the mouse hovers over the results for 1500ms.

**Comment by DavidGP** [comment]
Yes please. 

And why not have the preview open automatically on _any_ link after the delay time?

**Comment by boromyr** [comment]
[Prevue PopUp.zip](https://github.com/degecko/prevue/files/14470427/Prevue.PopUp.zip)
Here you go, let me know if it works but I can't guarantee it, it's a customized version.
If you want, you can modify prevue.js yourself, my modifications start at line 14. At line 19, you can choose your shortcut keys, ctrl+shift+up by default. If you want it to always work with the timeout, comment out lines 29, 35, 38, 44.
Let me know what happens when you try to open the preview from Google results for Stack Exchange sites, there might be a bug.

**Comment by DavidGP** [comment]
Thanks very much will try! Yes, I noticed that bug on Stackexchange as well.

**Comment by DavidGP** [comment]
Yeah, works! I have commented out lines 29, 35, 38, 44, but still have to press my hotkey "Alt" for the preview to work.
Is there a way to have the preview come up after xxx milliseconds without hotkey?

**Comment by DavidGP** [comment]
Oops it does funny things on Gmail. Can I exclude certain pages by a blacklist or something...?

**Comment by boromyr** [comment]
Yes, line 19 column 111, add `&& !window.location.href.includes("x")` for every site you want to exclude, replace x with the partial name of the site.

**Comment by DavidGP** [comment]
That seems to be here, is that correct?

![image](https://github.com/degecko/prevue/assets/1527716/6a4410d4-e804-4a90-ba25-f6bc4f2e44e2)

**Comment by boromyr** [comment]
sorry line 29, I hit the wrong button

**Comment by boromyr** [comment]
> Grazie mille ci proverò! Sì, ho notato quel bug anche su Stackexchange.

What exactly happens to you on Stackexchange sites? Do they redirect you directly to the link of the question page on the current tab? 

Were you able to make it work as you wanted?

**Comment by degecko** [comment]
Sorry, I don't provide Edge support.

**Comment by boromyr** [comment]
Is it possible to block redirection on Stackexchange sites?
