### ISSUE TITLE
【Request】Add split screen

### ISSUE THREAD

**Issue by Noah1995** [degecko/prevue#4]
1丶Like [【ezLinkPreview】](https://www.crx4chrome.com/extensions/nnkcfbiefgdaceeplickkkmifpicbpcc/)
The ChromeStore has been removed at present
![image](https://user-images.githubusercontent.com/25548230/185755176-f2191672-d942-4bb5-87f4-e952fa4331af.png)

2丶Maybe you can try to add [【EdgeTranslate】](https://github.com/EdgeTranslate/EdgeTranslate)drag method...
Switch between popup preview and split screen.
![录制_2022_08_20_23_33_54_729](https://user-images.githubusercontent.com/25548230/185755361-75dcfe7f-2d5b-4785-b885-3340cfa29730.gif)

3丶I use the whale browser to demonstrate
![录制_2022_09_01_00_22_08_311](https://user-images.githubusercontent.com/25548230/187730067-9f37d91c-9e98-4cbc-aa15-fb8175cf8147.gif)

**Comment by Noah1995** [comment]
In addition, can you add the functions of [Link Previewer](https://chrome.google.com/webstore/detail/link-previewer/hhnejjlimgamhpolpjnjdkdcoclldhli)?
For now. The browser's built-in web page translation feature can not be translated

![image](https://user-images.githubusercontent.com/25548230/194636330-6d33e9ed-60ce-47a8-b29a-7e2d7e67fcfd.png)

**Comment by degecko** [comment]
Sorry, this doesn't match the scope of this project.
