### ISSUE TITLE
Unable to preview meta.appinn.net

### ISSUE THREAD

**Issue by wordpure** [degecko/prevue#7]
The extension doesn't work on meta.appinn.net, the iframe prompts [meta.appinn.net](https://meta.appinn.net/) to forbid embedding.

browser: Firefox 106
extension: 0.4.4

![图片](https://user-images.githubusercontent.com/68013962/194200694-9ba7880b-205c-4be5-b77e-c12006c6851f.png)

**Comment by degecko** [comment]
It should be working now. Please make sure that you use the current latest version (0.4.6).
