### ISSUE TITLE
Unable to preview moegirl.org and bilibili bv video

### ISSUE THREAD

**Issue by wordpure** [degecko/prevue#8]
When previewing Moegirlpedia, for example, <https://zh.moegirl.org.cn/Mainpage>, the iframe prompts that the webpage is forbidden to be embedded.

![图片](https://user-images.githubusercontent.com/68013962/195134950-58d36cc2-e8a8-42d4-ad1d-f74738220fb4.png)

When previewing bilibili bv video page, for example, <https://www.bilibili.com/video/BV1jx411c7Qm>, the url corresponding to the iframe will be automatically opened on the current web page.

![preview bilibili bv video](https://user-images.githubusercontent.com/68013962/195139851-e0306844-7d80-4475-a66d-8bb2f72ed83d.gif)

Browser: Firefox 106
Extension: 0.4.7

**Comment by Noah1995** [comment]
你可以试一下[Link Previewer](https://chrome.google.com/webstore/detail/link-previewer/hhnejjlimgamhpolpjnjdkdcoclldhli)
我用过的目前只有这个扩展有防止当前页面跳转
但是没有Prevue Popup操作逻辑好
![image](https://user-images.githubusercontent.com/25548230/208246905-12fd172f-8198-4b1c-b4bb-e75381fb1d37.png)

**Comment by wordpure** [comment]
> 你可以试一下[Link Previewer](https://chrome.google.com/webstore/detail/link-previewer/hhnejjlimgamhpolpjnjdkdcoclldhli)

感谢推荐。

这个扩展我之前用过，不知为何加载很慢，而且不能解除网站的 x-frame-options 限制，后面就没用了😂

不过 Prevue 现在好像也不能绕过 x-frame-options 了，我都是用 Header Editor 移除响应头后才能正常预览的。

**Comment by Noah1995** [comment]
> > 你可以试一下 [Link Previewer](https://chrome.google.com/webstore/detail/link-previewer/hhnejjlimgamhpolpjnjdkdcoclldhli)
> 
> 感谢推荐。
> 
> 这个扩展我之前用过，不知为何加载很慢，而且不能解除网站的 x-frame-options 限制，后面就没用了😂
> 
> 不过 Prevue 现在好像也不能绕过 x-frame-options 了，我都是用 Header Editor 移除响应头后才能正常预览的。

不知道什么是 x-frame-options...
什么作用啊

**Comment by wordpure** [comment]
> 什么作用啊

扩展是通过将站点作为 Iframe 嵌入来实现网页预览的。但如果站点的响应头里设置了 X-Frame-Options，它就不支持被嵌入在 Iframe 里了，所以要把它移除掉。

具体解释可以看它的 MDN 文档 [X-Frame-Options - HTTP | MDN](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/X-Frame-Options)

**Comment by degecko** [comment]
This is a limitation implemented by the website itself. It figures out it's being opened in an iframe and it breaks out of it. I've noticed Reddit doing this as well.

Unfortunately, I can't do anything about it without hacking the website's code to break their own breakout code. I would do that if there was a way to make absolutely sure I don't introduce unforeseen bugs, but the amount of websites that might do that same thing introduces infinite specific scenarios to hack and I choose not to mess with it in the first place.
